// ============================================================
//  JARVIS MUSIC — Static Data
// ============================================================

const PLAYLISTS = [
  {
    id: "pl1",
    title: "Chill Vibes 2025",
    description: "The perfect soundtrack for focus and relaxation",
    emoji: "🌿",
    color: "#1a4a2e",
    trackCount: 32,
    owner: "Jarvis",
  },
  {
    id: "pl2",
    title: "Late Night Drive",
    description: "Dark synth, lo-fi, and midnight energy",
    emoji: "🌙",
    color: "#1a1a3e",
    trackCount: 24,
    owner: "Jarvis",
  },
  {
    id: "pl3",
    title: "Morning Boost",
    description: "Start your day with high-energy beats",
    emoji: "☀️",
    color: "#4a2e00",
    trackCount: 18,
    owner: "Jarvis",
  },
  {
    id: "pl4",
    title: "Workout Anthems",
    description: "Power through every rep and set",
    emoji: "🏋️",
    color: "#4a0e0e",
    trackCount: 40,
    owner: "Jarvis",
  },
  {
    id: "pl5",
    title: "R&B Classics",
    description: "Timeless soul and rhythm from the greats",
    emoji: "🎷",
    color: "#2e1a4a",
    trackCount: 27,
    owner: "Jarvis",
  },
  {
    id: "pl6",
    title: "Hip-Hop Heat",
    description: "The hottest bars and beats right now",
    emoji: "🎤",
    color: "#0e2a4a",
    trackCount: 35,
    owner: "Jarvis",
  },
  {
    id: "pl7",
    title: "Acoustic Sessions",
    description: "Stripped-back, intimate, and beautiful",
    emoji: "🎸",
    color: "#3a2a1a",
    trackCount: 22,
    owner: "Jarvis",
  },
  {
    id: "pl8",
    title: "Electronic Pulse",
    description: "Deep house, techno, and beyond",
    emoji: "⚡",
    color: "#0e3a4a",
    trackCount: 29,
    owner: "Jarvis",
  },
];

const TOP_TRACKS = [
  {
    id: "t1",
    title: "Blinding Lights",
    artist: "The Weeknd",
    album: "After Hours",
    duration: "3:20",
    emoji: "🌃",
    color: "#4a1a2e",
    liked: true,
  },
  {
    id: "t2",
    title: "As It Was",
    artist: "Harry Styles",
    album: "Harry's House",
    duration: "2:37",
    emoji: "🏠",
    color: "#1a4a3a",
    liked: false,
  },
  {
    id: "t3",
    title: "Flowers",
    artist: "Miley Cyrus",
    album: "Endless Summer Vacation",
    duration: "3:21",
    emoji: "🌸",
    color: "#3a2e1a",
    liked: true,
  },
  {
    id: "t4",
    title: "Anti-Hero",
    artist: "Taylor Swift",
    album: "Midnights",
    duration: "3:20",
    emoji: "🦸",
    color: "#1a1a4a",
    liked: false,
  },
  {
    id: "t5",
    title: "Creepin'",
    artist: "Metro Boomin, The Weeknd",
    album: "Heroes & Villains",
    duration: "3:03",
    emoji: "🌙",
    color: "#2a1a4a",
    liked: true,
  },
  {
    id: "t6",
    title: "Kill Bill",
    artist: "SZA",
    album: "SOS",
    duration: "2:33",
    emoji: "⚔️",
    color: "#4a1a1a",
    liked: false,
  },
  {
    id: "t7",
    title: "Rich Flex",
    artist: "Drake & 21 Savage",
    album: "Her Loss",
    duration: "3:55",
    emoji: "💎",
    color: "#2a2a1a",
    liked: true,
  },
  {
    id: "t8",
    title: "Unholy",
    artist: "Sam Smith ft. Kim Petras",
    album: "Gloria",
    duration: "2:37",
    emoji: "🔥",
    color: "#4a2a1a",
    liked: false,
  },
  {
    id: "t9",
    title: "Calm Down",
    artist: "Rema & Selena Gomez",
    album: "Rave & Roses",
    duration: "3:59",
    emoji: "🌊",
    color: "#1a3a4a",
    liked: false,
  },
  {
    id: "t10",
    title: "Snooze",
    artist: "SZA",
    album: "SOS",
    duration: "3:21",
    emoji: "🛌",
    color: "#3a1a4a",
    liked: true,
  },
];

const NEW_RELEASES = [
  {
    id: "nr1",
    title: "Utopia",
    artist: "Travis Scott",
    type: "Album",
    year: 2025,
    emoji: "🚀",
    color: "#1a2a4a",
  },
  {
    id: "nr2",
    title: "Eternal Sunshine",
    artist: "Ariana Grande",
    type: "Album",
    year: 2025,
    emoji: "☀️",
    color: "#4a3a1a",
  },
  {
    id: "nr3",
    title: "Vultures 3",
    artist: "Kanye West",
    type: "Album",
    year: 2025,
    emoji: "🦅",
    color: "#2a1a1a",
  },
  {
    id: "nr4",
    title: "GNX",
    artist: "Kendrick Lamar",
    type: "Album",
    year: 2025,
    emoji: "🎭",
    color: "#1a4a4a",
  },
  {
    id: "nr5",
    title: "Short n' Sweet",
    artist: "Sabrina Carpenter",
    type: "Album",
    year: 2025,
    emoji: "🍭",
    color: "#4a1a3a",
  },
  {
    id: "nr6",
    title: "Diamond Jubilee",
    artist: "Cindy Lee",
    type: "Album",
    year: 2025,
    emoji: "💠",
    color: "#0e3a3a",
  },
];

const RECENTLY_PLAYED = [
  { id: "rp1", title: "Chill Vibes 2025", type: "Playlist", emoji: "🌿", color: "#1a4a2e" },
  { id: "rp2", title: "After Hours", type: "Album · The Weeknd", emoji: "🌃", color: "#4a1a2e" },
  { id: "rp3", title: "Midnights", type: "Album · Taylor Swift", emoji: "🌙", color: "#1a1a4a" },
  { id: "rp4", title: "Workout Anthems", type: "Playlist", emoji: "🏋️", color: "#4a0e0e" },
  { id: "rp5", title: "SOS", type: "Album · SZA", emoji: "🆘", color: "#4a1a1a" },
  { id: "rp6", title: "Electronic Pulse", type: "Playlist", emoji: "⚡", color: "#0e3a4a" },
];

const QUICK_ACCESS = [
  { id: "qa1", title: "Liked Songs", emoji: "💜", color: "#450e2c" },
  { id: "qa2", title: "Recently Played", emoji: "🕐", color: "#1a2a4a" },
  { id: "qa3", title: "Top Mixes", emoji: "🎯", color: "#1a4a2e" },
  { id: "qa4", title: "Discover Weekly", emoji: "🔍", color: "#2a1a4a" },
  { id: "qa5", title: "Daily Mix 1", emoji: "1️⃣", color: "#3a1a2a" },
  { id: "qa6", title: "Daily Mix 2", emoji: "2️⃣", color: "#1a3a2a" },
];

const GENRES = [
  { id: "g1", name: "Pop", emoji: "🎵", color: "#e91e63" },
  { id: "g2", name: "Hip-Hop", emoji: "🎤", color: "#ff5722" },
  { id: "g3", name: "R&B", emoji: "🎷", color: "#9c27b0" },
  { id: "g4", name: "Electronic", emoji: "⚡", color: "#2196f3" },
  { id: "g5", name: "Rock", emoji: "🎸", color: "#f44336" },
  { id: "g6", name: "Jazz", emoji: "🎺", color: "#ff9800" },
  { id: "g7", name: "Classical", emoji: "🎻", color: "#795548" },
  { id: "g8", name: "Country", emoji: "🤠", color: "#8d6e63" },
  { id: "g9", name: "Latin", emoji: "💃", color: "#e91e63" },
  { id: "g10", name: "K-Pop", emoji: "🌸", color: "#e91e63" },
  { id: "g11", name: "Afrobeats", emoji: "🥁", color: "#4caf50" },
  { id: "g12", name: "Lo-Fi", emoji: "📻", color: "#607d8b" },
];
